[package]
name = "gamer"
version = "0.1.0"
authors = ["Steve Trout <steve.trout@gmail.com>"]

[profile.release]
debug = true
lto = true

[dependencies]
rand = "*"
bit-set = "*"
quickcheck = "*"
vec_map = "*"
